apiVersion: v1
kind: Service
metadata:
  name: {{ include "register-job.fullname" . }}
  labels:
    {{- include "register-job.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: refereeport
      protocol: TCP
      name: refereeserviceport
  selector:
    {{- include "register-job.selectorLabels" . | nindent 4 }}
